// <auto-generated />
using System;
using DashInvestimentos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DashInvestimentos.Migrations
{
    [DbContext(typeof(DashInvestimentosContext))]
    [Migration("20200816190631_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DashInvestimentos.Models.Movimentacao", b =>
                {
                    b.Property<int>("MovimentacaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperacaoId");

                    b.Property<string>("Tipo");

                    b.Property<float>("ValorCompra");

                    b.Property<float>("ValorVenda");

                    b.HasKey("MovimentacaoId");

                    b.HasIndex("OperacaoId")
                        .IsUnique();

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("DashInvestimentos.Models.Operacao", b =>
                {
                    b.Property<int>("OperacaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ativo");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Quantidade");

                    b.HasKey("OperacaoId");

                    b.ToTable("Operacao");
                });

            modelBuilder.Entity("DashInvestimentos.Models.Movimentacao", b =>
                {
                    b.HasOne("DashInvestimentos.Models.Operacao", "Operacao")
                        .WithOne("Movimentacao")
                        .HasForeignKey("DashInvestimentos.Models.Movimentacao", "OperacaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
